services:
  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/restaurant_management
      JWT_SECRET: change_me_to_a_long_random_string
      ADMIN_KEY: change_me_admin_key
    depends_on:
      - mongo
volumes:
  mongo_data:
